name: Run Trello API Collection with HTML Report

on:
  push:
    branches:
      - main

jobs:
  run-postman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman and HTML Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman Collection with HTML Report
        run: |
          newman run TrelloAPI.postman_collection.json \
            --environment Staging_Trello.postman_environment.json \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export docs/html-report.html
        continue-on-error: true

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: postman-html-report
          path: docs/html-report.html

      - name: Commit HTML report to docs folder
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add docs/html-report.html
          git commit -m "Add HTML report for GitHub Pages"
          git push
