name: Run Postman Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman collection
        run: |
          newman run TrelloAPI.postman_collection.json \
            -e Staging_Trello.postman_environment.json \
            --reporters cli,junit \
            --reporter-junit-export reports/junit-report.xml

      - name: Upload Test Report
        uses: actions/upload-artifact@v2.2.4
        with:
          name: postman-report
          path: reports/
