name: Run Postman with HTML Report

on:
  push:
    branches:
      - main

jobs:
  run-postman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman and HTML Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman Collection with HTML Report
        run: |
          newman run TrelloAPI.postman_collection.json \
            --environment Staging_Trello.postman_environment.json \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export newman/html-report.html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: postman-html-report
          path: newman/html-report.html
